interface ZIF_CDS_I_BOOKINGS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_I_BOOKINGS,
 CREATE_ZCDS_I_BOOKINGS         TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C713CB',
 DELETE_ZCDS_I_BOOKINGS         TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C793CB',
 LOCK_ZCDS_I_BOOKINGS           TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C653CB',
 SAVE_ZCDS_I_BOOKINGS           TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C813CB',
 UNLOCK_ZCDS_I_BOOKINGS         TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C693CB',
 UPDATE_ZCDS_I_BOOKINGS         TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C753CB',
 VALIDATE_ZCDS_I_BOOKINGS       TYPE /BOBF/ACT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C7D3CB',
      END OF ZCDS_I_BOOKINGS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_I_BOOKINGS,
        BEGIN OF LOCK_ZCDS_I_BOOKINGS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZCDS_I_BOOKINGS,
        BEGIN OF UNLOCK_ZCDS_I_BOOKINGS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZCDS_I_BOOKINGS,
      END OF ZCDS_I_BOOKINGS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCDS_I_BOOKINGS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C290F2DC31EED92FC0ECDFB6693CB',
      END OF ZCDS_I_BOOKINGS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_I_BOOKINGS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C633CB',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C5F3CB',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C6F3CB',
      END OF ZCDS_I_BOOKINGS,
      BEGIN OF ZCDS_I_BOOKINGS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C873CB',
      END OF ZCDS_I_BOOKINGS_LOCK,
      BEGIN OF ZCDS_I_BOOKINGS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C853CB',
      END OF ZCDS_I_BOOKINGS_MESSAGE,
      BEGIN OF ZCDS_I_BOOKINGS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C290F2DC31EED92FC0EB7E5C893CB',
      END OF ZCDS_I_BOOKINGS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_I_BOOKINGS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_I_BOOKINGS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C290F2DC31EED92FC0EB7E5C553CB' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_I_BOOKINGS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_I_BOOKINGS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C290F2DC31EED92FC0ECDFB66B3CB',
 SET_BOOKING_ID                 TYPE /BOBF/DET_KEY VALUE '000C290F2DC31EED93804B5F7F2CB6FD',
      END OF ZCDS_I_BOOKINGS,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_I_BOOKINGS                TYPE /BOBF/OBM_NODE_KEY VALUE '000C290F2DC31EED92FC0EB7E5C593CB',
 ZCDS_I_BOOKINGS_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '000C290F2DC31EED92FC0EB7E5C613CB',
 ZCDS_I_BOOKINGS_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '000C290F2DC31EED92FC0EB7E5C5D3CB',
 ZCDS_I_BOOKINGS_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '000C290F2DC31EED92FC0EB7E5C6D3CB',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_I_BOOKINGS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CONNID                         TYPE STRING VALUE 'CONNID',
  FLDATE                         TYPE STRING VALUE 'FLDATE',
  BOOKID                         TYPE STRING VALUE 'BOOKID',
  CUSTOMID                       TYPE STRING VALUE 'CUSTOMID',
  CUSTTYPE                       TYPE STRING VALUE 'CUSTTYPE',
  SMOKER                         TYPE STRING VALUE 'SMOKER',
  LUGGWEIGHT                     TYPE STRING VALUE 'LUGGWEIGHT',
  WUNIT                          TYPE STRING VALUE 'WUNIT',
  INVOICE                        TYPE STRING VALUE 'INVOICE',
  CLASS                          TYPE STRING VALUE 'CLASS',
  FORCURAM                       TYPE STRING VALUE 'FORCURAM',
  FORCURKEY                      TYPE STRING VALUE 'FORCURKEY',
  LOCCURAM                       TYPE STRING VALUE 'LOCCURAM',
  ORDER_DATE                     TYPE STRING VALUE 'ORDER_DATE',
      END OF ZCDS_I_BOOKINGS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_I_BOOKINGS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C290F2DC31EED92FC0EB7E5C5B3CB',
      END OF ZCDS_I_BOOKINGS,
    END OF SC_NODE_CATEGORY .
endinterface.
